name: Benchmark Stats

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repository
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Get benchmark stats
        run: cd benchmarks && python get_benchmark_stats.py > readme.md # Script to parse benchmark data
      - name: Commit Updates
        run: git config --global user.email "ruidong@umich.edu"
              && git config --global user.name "Rui Dong"
              && git add . 
              && git commit -m "Updating readme with updated results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      

