name: Benchmark Stats

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repository
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get benchmark stats
        run: python benchmarks/get_benchmark_stats.py > benchmarks/readme.md # Script to parse benchmark data
      - name: Commit Updates
        run: git config --global user.email "ruidong@umich.edu"
              && git config --global user.name "Rui Dong"
              && git add . 
              && git commit -m "Updating readme with updated results"
              && git push origin main
      

